#!/bin/bash

# دليل اختبار سريع لمشكلة الماتشينج

echo "=========================================="
echo "📊 دليل اختبار الماتشينج على Dashboard"
echo "=========================================="
echo ""

echo "الخطوة 1️⃣: تأكد من تشغيل جميع الخدمات"
echo "=========================================="
echo "✅ Backend: http://localhost:5000"
echo "✅ Frontend: http://localhost:5174"
echo "✅ ML Service (optional): http://localhost:5002"
echo ""

echo "الخطوة 2️⃣: تسجيل الدخول"
echo "=========================================="
echo "1. اذهب إلى http://localhost:5174"
echo "2. اختر 'Employee' من القائمة المنسدلة"
echo "3. سجل دخول أو سجل حساب جديد"
echo ""

echo "الخطوة 3️⃣: رفع Resume (مهم!)"
echo "=========================================="
echo "1. اذهب إلى صفحة Profile الخاصة بك"
echo "2. ابحث عن 'Upload CV' أو 'Upload Resume'"
echo "3. اختر ملف PDF"
echo "4. اضغط Upload وانتظر المعالجة"
echo ""

echo "الخطوة 4️⃣: فتح Console للتحقق"
echo "=========================================="
echo "1. اضغط F12 (أو Ctrl+Shift+I)"
echo "2. اختر 'Console' Tab"
echo "3. اذهب إلى Dashboard"
echo ""

echo "الخطوة 5️⃣: شوف الـ Logs المتوقعة"
echo "=========================================="
echo "✅ يجب تشوف رسائل مثل:"
echo "   🔄 Fetching jobs for dashboard..."
echo "   ✅ Jobs data received from API:"
echo "   📊 First job matchScore: 85.5"
echo "   📊 Second job matchScore: 78.2"
echo ""

echo "الخطوة 6️⃣: تفقد Backend Logs (في Terminal)"
echo "=========================================="
echo "✅ يجب تشوف رسائل مثل:"
echo "   📊 Calculating match scores for user with role: employee"
echo "   🔍 Matching CV against 10 jobs..."
echo "   ✅ Used Python BERT matcher"
echo "   أو"
echo "   ✅ Used Hybrid matcher as fallback"
echo ""

echo "الخطوة 7️⃣: تحقق من النتائج"
echo "=========================================="
echo "✅ الوظائف يجب أن تظهر مع نسب match (مثل 85% Match)"
echo "✅ الوظائف يجب أن تكون مرتبة من الأفضل للأقل"
echo "✅ كل وظيفة لها شارة خضراء مع النسبة"
echo ""

echo "🔍 إذا كان هناك مشكلة:"
echo "=========================================="
echo "❌ لا تظهر الـ scores:"
echo "   1. تأكد من رفع Resume في Profile"
echo "   2. شوف الـ logs في Console"
echo "   3. شوف Backend logs في Terminal"
echo ""
echo "❌ كل الـ scores = 0:"
echo "   1. قد يكون Resume فارغ أو بدون skills"
echo "   2. جرب Resume آخر"
echo ""
echo "❌ الخطأ: 'No resume found':"
echo "   1. رفع Resume أولاً في Profile page"
echo "   2. انتظر حتى ينتهي الرفع"
echo "   3. ارجع للـ Dashboard"
echo ""

echo "=========================================="
echo "✅ لو كل شيء تمام التمام:"
echo "=========================================="
echo "الماتشينج يجب أن يشتغل بشكل صحيح الآن! 🎉"
echo ""

# اختبار سريع (اختياري)
echo "اختبار سريع من Terminal:"
echo "=========================================="
echo "curl -H 'Authorization: Bearer YOUR_TOKEN' http://localhost:5000/api/jobs"
echo ""

echo "استبدل YOUR_TOKEN بـ token الخاص بك من:"
echo "localStorage.getItem('token') (في Console)"
